export enum CollectorWalletTransactionType {
  COLLECTION = 'COLLECTION',
  WITHDRAWAL = 'WITHDRAWAL',
  ROUTE_EXPENSE = 'ROUTE_EXPENSE',
  LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT',
  CASH_ADJUSTMENT = 'CASH_ADJUSTMENT',
}

