export enum SafeTransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  EXPENSE = 'EXPENSE',
  TRANSFER_TO_COLLECTOR = 'TRANSFER_TO_COLLECTOR',
  TRANSFER_FROM_COLLECTOR = 'TRANSFER_FROM_COLLECTOR',
  TRANSFER_TO_SAFE = 'TRANSFER_TO_SAFE',
  TRANSFER_FROM_SAFE = 'TRANSFER_FROM_SAFE',
}

