export enum WalletTransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  LOAN_DISBURSEMENT = 'LOAN_DISBURSEMENT',
  LOAN_PAYMENT = 'LOAN_PAYMENT',
  TRANSFER_TO_MANAGER = 'TRANSFER_TO_MANAGER',
  TRANSFER_FROM_SUBADMIN = 'TRANSFER_FROM_SUBADMIN',
}
